gitea_urls:
  api: https://codeberg.org/api/v1/
  download: https://codeberg.org
  skip_tls_verify: false

before:
  hooks:
    - go mod download
builds:
  - id: coredns
    main: ./cmd/coredns.go
    binary: coredns
    ldflags:
      - -X main.pluginVersion={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
