name: "Charts: Test"

on:
  workflow_call:
    inputs:
      checkoutCommit:
        required: true
        type: string
      chartsToTest:
        description: >
          A JSON encoded array of charts to lint
        type: string
        required: true
      overrideDeps:
        description: >
          A JSON encoded array of dependencies to override before testing
        type: string
        required: false
        default: "[]"

env:
  HELM_VERSION: 3.17.2

jobs:
  install-chart:
    name: Install chart
    runs-on: docker
    if: ${{ inputs.chartsToTest != '[]' && inputs.chartsToTest != '' }}
    strategy:
      matrix:
        chart: ${{ fromJSON(inputs.chartsToTest) }}
        k8s_version: ["v1.32.3"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh --version "v${{ env.HELM_VERSION }}"
          rm get_helm.sh

      - name: Install kubectl
        run: |
          curl -fsSL -o /usr/local/bin/kubectl "https://dl.k8s.io/release/${{ matrix.k8s_version }}/bin/linux/amd64/kubectl"
          chmod +x /usr/local/bin/kubectl

      - name: Install Python
        run: |
          apt-get update
          apt-get install -y --no-install-recommends python3 python3-pip

      - name: Set up chart-testing
        uses: https://github.com/helm/chart-testing-action@v2.8.0

      - name: Debug
        run: |
          kubectl config view
          env

      - name: Create k3d cluster
        uses: https://github.com/nolar/setup-k3d-k3s@v1
        with:
          version: ${{ matrix.k8s_version }}

      - name: Remove node taints
        run: |
          kubectl taint --all=true nodes node.cloudprovider.kubernetes.io/uninitialized- || true

      - name: Run chart-testing (install)
        run: ct install --config .ci/ct.yaml --charts "${{ matrix.chart }}" --helm-extra-set-args '--set=domain=example.com --set=watchedResources[0]=HTTPRoute'

  # Summarize matrix https://github.community/t/status-check-for-a-matrix-jobs/127354/7
  install_success:
    needs:
      - install-chart
    if: |
      always()
    name: Install successful
    runs-on: docker
    steps:
      - name: Check install matrix status
        if: ${{ (inputs.chartsToTest != '[]' && inputs.chartsToTest != '') && needs.install-chart.result != 'success' }}
        run: exit 1

  unittest-chart:
    name: Unit-test chart
    runs-on: docker
    if: ${{ inputs.chartsToTest != '[]' && inputs.chartsToTest != '' }}
    strategy:
      matrix:
        chart: ${{ fromJSON(inputs.chartsToTest) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh --version "v${{ env.HELM_VERSION }}"
          rm get_helm.sh

      - name: Run tests
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest --version 0.8.1
          helm dep update "${{ matrix.chart }}"
          helm unittest "${{ matrix.chart }}"

  # Summarize matrix https://github.community/t/status-check-for-a-matrix-jobs/127354/7
  unittest_success:
    needs:
      - unittest-chart
    if: |
      always()
    name: Unittest successful
    runs-on: docker
    steps:
      - name: Check unittest matrix status
        if: ${{ (inputs.chartsToTest != '[]' && inputs.chartsToTest != '') && needs.unittest-chart.result != 'success' }}
        run: exit 1
