name: "Pull Request: Get metadata"

on:
  workflow_call:
    outputs:
      isRenovatePR:
        description: "Is the PR coming from Renovate?"
        value: ${{ jobs.pr-metadata.outputs.isRenovatePR }}
      isFork:
        description: "Is the PR coming from a forked repo?"
        value: ${{ jobs.pr-metadata.outputs.isFork }}
      changedFiles:
        description: "A list of the files changed in this PR"
        value: ${{ jobs.pr-changes.outputs.changed-files }}

jobs:
  pr-metadata:
    name: Collect PR metadata
    runs-on: docker
    outputs:
      isRenovatePR: ${{ startsWith(steps.branch-name.outputs.current_branch, 'renovate/') }}
      isFork: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    steps:
      - name: Get branch name
        id: branch-name
        uses: https://github.com/tj-actions/branch-names@v9.0.2

      - name: Save PR data to file
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > pr_number.txt

      - name: Store pr data in artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: pr_metadata
          path: ./pr_number.txt
          retention-days: 5

  pr-changes:
    name: Collect PR changes
    runs-on: docker
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: https://github.com/bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        with:
          patterns: charts/**
