name: "Pull Request: Get metadata"

on:
  workflow_call:
    outputs:
      isRenovatePR:
        description: "Is the PR coming from Renovate?"
        value: ${{ jobs.pr-metadata.outputs.isRenovatePR }}
      isFork:
        description: "Is the PR coming from a forked repo?"
        value: ${{ jobs.pr-metadata.outputs.isFork }}

jobs:
  pr-metadata:
    name: Collect PR metadata
    runs-on: docker
    outputs:
      isRenovatePR: ${{ startsWith(steps.branch-name.outputs.current_branch, 'renovate/') }}
      isFork: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    steps:
      - name: Get branch name
        id: branch-name
        uses: https://github.com/tj-actions/branch-names@v9.0.2

      - name: Save PR data to file
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > pr_number.txt

      - name: Store pr data in artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: pr_metadata
          path: ./pr_number.txt
          retention-days: 5
