name: "Pull Request: Validate"

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  pr-info:
    name: Collect PR metadata
    runs-on: codeberg-tiny-lazy
    outputs:
      isRenovatePR: ${{ startsWith(github.head_ref, 'renovate/') && 'true' || 'false' }}
      isFork: ${{ github.event.pull_request.head.repo.full_name != github.repository && 'true' || 'false' }}
    steps:
      - name: Save PR data to file
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > pr_number.txt

      - name: Store pr data in artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: pr_metadata
          path: ./pr_number.txt
          retention-days: 5

  pr-changes:
    name: Collect PR changes
    runs-on: codeberg-tiny-lazy
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: https://github.com/bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        with:
          patterns: charts/**

  pre-commit:
    uses: ./.forgejo/workflows/pre-commit-check.yaml
    needs:
      - pr-changes
    with:
      modifiedFiles: ${{ needs.pr-changes.outputs.changed-files }}

  charts-lint:
    uses: ./.forgejo/workflows/charts-lint.yaml
    if: contains(needs.pr-changes.outputs.changed-files, 'charts/')
    needs:
      - pr-info
      - pr-changes
    with:
      checkoutCommit: ${{ github.sha }}
      chartsToLint: '["charts/k8s-gateway"]'
      isRenovatePR: ${{ needs.pr-info.outputs.isRenovatePR }}

  charts-test:
    uses: ./.forgejo/workflows/charts-test.yaml
    if: contains(needs.pr-changes.outputs.changed-files, 'charts/')
    needs:
      - pr-changes
    with:
      checkoutCommit: ${{ github.sha }}
      chartsToTest: '["charts/k8s-gateway"]'
