name: "Pre-commit consistency check"

on:
  workflow_call:
    inputs:
      modifiedFiles:
        description: >
          A JSON encoded array of files to check. If omitted, all files are
          checked.
        required: false
        type: string
        default: "[]"

jobs:
  pre-commit-check:
    name: Run pre-commit checks
    runs-on: codeberg-tiny
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - uses: https://github.com/actions/setup-go@v6
        with:
          go-version: stable

      - name: Run pre-commit
        env:
          EXTRA_ARGS: >-
            ${{ inputs.modifiedFiles != '[]' && format('--files {0}', join(fromJson(inputs.modifiedFiles), ' ')) || '--all-files' }}
        run: |
          python3 -m venv .venv
          .venv/bin/pip install pre-commit
          .venv/bin/pre-commit run --config .ci/pre-commit/config.yaml ${EXTRA_ARGS}
