name: Pages
on:
  push:
    branches: ["pages"]
  workflow_dispatch:

jobs:
 publish:
  runs-on: codeberg-tiny
  steps:
   - uses: https://code.forgejo.org/actions/checkout@v4
   - uses: https://codeberg.org/git-pages/action@v2
     with:
      site: https://k8s-gateway.kryptonian.kapsi.fi/
      server: codeberg.page
      token: ${{ forge.token }}
      source: .
