name: "Charts: Lint"

on:
  workflow_call:
    inputs:
      checkoutCommit:
        required: true
        type: string
      isRenovatePR:
        required: true
        default: "false"
        type: string
      chartsToLint:
        description: >
          A JSON encoded array of charts to lint
        required: true
        type: string
        default: "[]"

env:
  HELM_VERSION: 3.17.2

jobs:
  lint-chart:
    if: ${{ inputs.chartsToLint != '[]' }}
    name: Lint chart
    strategy:
      matrix:
        chart: ${{ fromJSON(inputs.chartsToLint) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Verify chart version
        uses: bjw-s/helm-charts-actions/verify-chart-version@2025.2.0
        id: verify-chart-version
        with:
          chart: "${{ matrix.chart }}"

      - name: Verify chart changelog
        uses: bjw-s/helm-charts-actions/verify-chart-changelog@2025.2.0
        if: inputs.isRenovatePR != 'true'
        id: verify-chart-changelog
        with:
          chart: "${{ matrix.chart }}"

      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.12.0
        with:
          setup-tools: |
            helmv3
          helm: "${{ env.HELM_VERSION }}"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (install)
        run: ct lint --config .ci/ct.yaml --charts "${{ matrix.chart }}"

  # Summarize matrix https://github.community/t/status-check-for-a-matrix-jobs/127354/7
  lint_success:
    needs:
      - lint-chart
    if: |
      always()
    name: Lint successful
    runs-on: ubuntu-latest
    steps:
      - name: Check lint matrix status
        if: ${{ (inputs.chartsToLint != '' && inputs.chartsToLint != '[]') && (needs.lint-chart.result != 'success') }}
        run: exit 1
