name: "Pull Request: Validate"

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  pr-metadata:
    uses: ./.github/workflows/pr-metadata.yaml

  pre-commit-check:
    uses: ./.github/workflows/pre-commit-check.yaml
    needs:
      - pr-metadata
    with:
      modifiedFiles: ${{ needs.pr-metadata.outputs.changedFiles }}

  charts-lint:
    uses: ./.github/workflows/charts-lint.yaml
    needs:
      - pr-metadata
    with:
      checkoutCommit: ${{ github.sha }}
      chartsToLint: '["charts/k8s-gateway"]'
      isRenovatePR: ${{ needs.pr-metadata.outputs.isRenovatePR }}

  charts-test:
    uses: ./.github/workflows/charts-test.yaml
    needs:
      - pr-metadata
    with:
      checkoutCommit: ${{ github.sha }}
      chartsToTest: '["charts/k8s-gateway"]'
